# Generated by Django 6.0.3 on 2026-03-16 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DreamTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Dream XI', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Ground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=10)),
                ('logo_color', models.CharField(default='#1a8f5c', max_length=7)),
                ('is_ipl_team', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=80)),
                ('is_overseas', models.BooleanField(default=False, help_text='Overseas player for IPL purposes')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('role', models.CharField(choices=[('Batsman', 'Batsman'), ('Bowler', 'Bowler'), ('All-Rounder', 'All-Rounder'), ('WK-Batsman', 'Wicket-Keeper Batsman')], max_length=30)),
                ('batting_style', models.CharField(choices=[('Right-hand bat', 'Right-hand bat'), ('Left-hand bat', 'Left-hand bat')], default='Right-hand bat', max_length=50)),
                ('bowling_style', models.CharField(choices=[('Right-arm fast', 'Right-arm fast'), ('Right-arm medium', 'Right-arm medium'), ('Left-arm fast', 'Left-arm fast'), ('Left-arm medium', 'Left-arm medium'), ('Right-arm offbreak', 'Right-arm offbreak'), ('Right-arm legbreak', 'Right-arm legbreak'), ('Left-arm orthodox', 'Left-arm orthodox'), ('Left-arm chinaman', 'Left-arm chinaman'), ('Slow left-arm orthodox', 'Slow left-arm orthodox'), ('N/A', 'N/A')], default='N/A', max_length=50)),
                ('photo_url', models.URLField(blank=True, default='')),
                ('bio', models.TextField(blank=True, default='')),
                ('total_matches', models.IntegerField(default=0)),
                ('total_runs', models.IntegerField(default=0)),
                ('total_wickets', models.IntegerField(default=0)),
                ('batting_avg', models.FloatField(default=0.0)),
                ('bowling_avg', models.FloatField(default=0.0)),
                ('strike_rate', models.FloatField(default=0.0)),
                ('economy_rate', models.FloatField(default=0.0)),
                ('highest_score', models.IntegerField(default=0)),
                ('best_bowling', models.CharField(default='0/0', max_length=20)),
                ('centuries', models.IntegerField(default=0)),
                ('half_centuries', models.IntegerField(default=0)),
                ('catches', models.IntegerField(default=0)),
                ('stumpings', models.IntegerField(default=0)),
                ('ipl_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='players.team')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BowlingInnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('overs', models.FloatField(default=0.0)),
                ('maidens', models.IntegerField(default=0)),
                ('runs_conceded', models.IntegerField(default=0)),
                ('wickets', models.IntegerField(default=0)),
                ('economy', models.FloatField(default=0.0)),
                ('phase', models.CharField(choices=[('powerplay', 'Powerplay (1-6)'), ('middle', 'Middle Overs (7-15)'), ('death', 'Death Overs (16-20)')], default='middle', max_length=20)),
                ('ground', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='players.ground')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bowling_innings', to='players.player')),
                ('opponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bowling_against', to='players.team')),
            ],
            options={
                'verbose_name_plural': 'Bowling innings',
            },
        ),
        migrations.CreateModel(
            name='BattingInnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('runs', models.IntegerField(default=0)),
                ('balls_faced', models.IntegerField(default=0)),
                ('fours', models.IntegerField(default=0)),
                ('sixes', models.IntegerField(default=0)),
                ('strike_rate', models.FloatField(default=0.0)),
                ('is_not_out', models.BooleanField(default=False)),
                ('phase', models.CharField(choices=[('powerplay', 'Powerplay (1-6)'), ('middle', 'Middle Overs (7-15)'), ('death', 'Death Overs (16-20)')], default='middle', max_length=20)),
                ('ground', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='players.ground')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batting_innings', to='players.player')),
                ('opponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batting_against', to='players.team')),
            ],
            options={
                'verbose_name_plural': 'Batting innings',
            },
        ),
        migrations.CreateModel(
            name='DreamTeamSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.IntegerField()),
                ('role_label', models.CharField(blank=True, default='', max_length=30)),
                ('dream_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='players.dreamteam')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.player')),
            ],
            options={
                'ordering': ['slot_number'],
                'unique_together': {('dream_team', 'slot_number')},
            },
        ),
    ]
